"use client";

import { createPortal } from "react-dom";
import { useEffect, useState } from "react";
import {
  AiGenerationProgress,
  type AiGenerationProgressStatus,
  responseProgressMessages,
} from "@/components/ui/ai-generation-progress";

type ResponseSettingsCardProps = {
  businessId: string;
  initialAutoGenerate: boolean;
  initialEnabledRatings: number[];
};

type GeneratedResponse = {
  responseText: string;
  reviewId: string;
  status: "ready";
};

function ratingStars(rating: number) {
  return `${"★".repeat(rating)}${"☆".repeat(5 - rating)}`;
}

async function readApiError(response: Response, fallback: string) {
  try {
    const data = await response.json();
    return typeof data?.error === "string" ? data.error : fallback;
  } catch {
    return fallback;
  }
}

export function ResponseSettingsCard({
  businessId,
  initialAutoGenerate,
  initialEnabledRatings,
}: ResponseSettingsCardProps) {
  const [autoGenerate, setAutoGenerate] = useState(initialAutoGenerate);
  const [enabledRatings, setEnabledRatings] = useState(initialEnabledRatings);
  const [isSaving, setIsSaving] = useState(false);
  const [progressStatus, setProgressStatus] =
    useState<AiGenerationProgressStatus>("idle");
  const [error, setError] = useState("");
  const [toast, setToast] = useState("");
  const [isRatingsSheetOpen, setIsRatingsSheetOpen] = useState(false);
  const [savedAutoGenerate, setSavedAutoGenerate] =
    useState(initialAutoGenerate);
  const [savedEnabledRatings, setSavedEnabledRatings] =
    useState(initialEnabledRatings);
  const isDirty =
    autoGenerate !== savedAutoGenerate ||
    enabledRatings.join(",") !== savedEnabledRatings.join(",");

  useEffect(() => {
    if (!toast) {
      return;
    }

    const timeout = window.setTimeout(() => setToast(""), 2000);
    return () => window.clearTimeout(timeout);
  }, [toast]);

  useEffect(() => {
    if (!isRatingsSheetOpen) {
      return;
    }

    const previousOverflow = document.body.style.overflow;
    const previousOverscrollBehavior = document.body.style.overscrollBehavior;
    document.body.style.overflow = "hidden";
    document.body.style.overscrollBehavior = "none";

    function onKeyDown(event: KeyboardEvent) {
      if (event.key === "Escape") {
        setIsRatingsSheetOpen(false);
      }
    }

    window.addEventListener("keydown", onKeyDown);
    return () => {
      window.removeEventListener("keydown", onKeyDown);
      document.body.style.overflow = previousOverflow;
      document.body.style.overscrollBehavior = previousOverscrollBehavior;
    };
  }, [isRatingsSheetOpen]);

  function toggleRating(rating: number, checked: boolean) {
    setEnabledRatings((currentRatings) =>
      checked
        ? [...currentRatings, rating].sort((a, b) => b - a)
        : currentRatings.filter((value) => value !== rating),
    );
  }

  async function handleSave() {
    setError("");
    setIsSaving(true);

    try {
      const response = await fetch("/api/responses/settings", {
        body: JSON.stringify({
          autoGenerate,
          businessId,
          enabledRatings,
        }),
        headers: {
          "Content-Type": "application/json",
        },
        method: "PATCH",
      });

      if (!response.ok) {
        throw new Error(
          await readApiError(response, "Nie udało się zapisać ustawień."),
        );
      }

      const data = await response.json();
      setAutoGenerate(Boolean(data?.autoGenerate));
      const savedRatings =
        Array.isArray(data?.enabledRatings)
          ? data.enabledRatings.map((value: unknown) => Number(value))
          : enabledRatings;
      setEnabledRatings(savedRatings);
      setSavedAutoGenerate(Boolean(data?.autoGenerate));
      setSavedEnabledRatings(savedRatings);

      if (data?.autoGenerate && enabledRatings.length > 0) {
        setProgressStatus("running");
        const autoGenerateResponse = await fetch("/api/responses/auto-generate", {
          body: JSON.stringify({
            businessId,
            enabledRatings,
          }),
          headers: {
            "Content-Type": "application/json",
          },
          method: "POST",
        });

        if (!autoGenerateResponse.ok) {
          throw new Error(
            await readApiError(
              autoGenerateResponse,
              "Nie udało się automatycznie wygenerować odpowiedzi.",
            ),
          );
        }

        const autoGenerateData = await autoGenerateResponse.json();
        const generatedCount = Number(autoGenerateData?.generatedCount ?? 0);
        const generatedResponses = Array.isArray(autoGenerateData?.generatedResponses)
          ? (autoGenerateData.generatedResponses as GeneratedResponse[])
          : [];

        if (generatedResponses.length > 0) {
          window.dispatchEvent(
            new CustomEvent("nuvorate:responses-generated", {
              detail: {
                generatedResponses,
              },
            }),
          );
        }

        setToast(
          generatedCount > 0
            ? `Wygenerowano ${generatedCount} ${
                generatedCount === 1 ? "odpowiedź" : "odpowiedzi"
              }`
            : "Brak nowych opinii do wygenerowania",
        );
        setProgressStatus("complete");
        window.setTimeout(() => setProgressStatus("idle"), 600);
      } else {
        setProgressStatus("idle");
        setToast("Zapisano");
      }
    } catch (saveError) {
      setError(
        saveError instanceof Error
          ? saveError.message
          : "Nie udało się zapisać ustawień.",
      );
      setProgressStatus("idle");
    } finally {
      setIsSaving(false);
    }
  }

  return (
    <section className="mt-8 rounded-[24px] border border-black/[0.06] bg-white p-5 shadow-card sm:p-6">
      <div className="hidden gap-5 min-[769px]:grid lg:grid-cols-[minmax(0,0.95fr)_minmax(300px,0.8fr)] lg:items-start">
        <div>
          <p className="text-xs font-medium uppercase tracking-[0.12em] text-black/35">
            Automatyczne odpowiedzi
          </p>
          <h2 className="mt-1 text-xl font-semibold tracking-tight">
            Ustawienia generowania
          </h2>
          <p className="mt-2 max-w-md text-sm leading-6 text-black/45">
            Wybierz oceny, dla których NuvoRate przygotuje propozycje odpowiedzi
            po zapisaniu ustawień.
          </p>
          <label className="mt-4 flex max-w-md items-center justify-between gap-4 rounded-2xl border border-black/[0.06] bg-[#FAFAFC] px-4 py-3 transition duration-200 hover:border-brand/20 hover:bg-white">
            <span>
              <span className="block text-sm font-semibold text-ink">
                Automatycznie generuj odpowiedzi
              </span>
              <span className="mt-1 block text-xs leading-5 text-black/40">
                NuvoRate przygotuje propozycje dla nowych opinii zgodnie z
                wybranymi ocenami.
              </span>
            </span>
            <input
              type="checkbox"
              checked={autoGenerate}
              onChange={(event) => setAutoGenerate(event.target.checked)}
              className="peer sr-only"
            />
            <span
              className={`nuvorate-switch-track relative h-6 w-11 shrink-0 rounded-full transition peer-focus-visible:ring-4 peer-focus-visible:ring-brand/20 ${
                autoGenerate ? "nuvorate-switch-track-on bg-brand" : "bg-black/10"
              }`}
            >
              <span
                className={`nuvorate-switch-thumb absolute top-1 h-4 w-4 rounded-full bg-white shadow-sm transition-transform duration-200 ${
                  autoGenerate ? "translate-x-6" : "translate-x-1"
                }`}
              />
            </span>
          </label>
        </div>
        <div className="flex flex-col gap-3">
          <p className="text-xs font-semibold uppercase tracking-[0.12em] text-black/35">
            Generuj dla ocen
          </p>
          <div className="grid gap-1.5">
            {[5, 4, 3, 2, 1].map((rating) => (
              <label
                key={rating}
                className="flex items-center justify-between gap-5 rounded-xl border border-black/[0.06] bg-[#FAFAFC] px-3.5 py-2 transition duration-200 hover:border-brand/20 hover:bg-white"
              >
                <span className="text-sm font-semibold tracking-[0.04em] text-ink">
                  {ratingStars(rating)}
                </span>
                <span className="flex items-center gap-2">
                  <span className="text-[10px] font-semibold uppercase tracking-[0.12em] text-black/30">
                    {enabledRatings.includes(rating) ? "ON" : "OFF"}
                  </span>
                  <input
                    type="checkbox"
                    checked={enabledRatings.includes(rating)}
                    onChange={(event) => toggleRating(rating, event.target.checked)}
                    className="peer sr-only"
                  />
                  <span
                    className={`nuvorate-switch-track relative h-6 w-11 rounded-full transition peer-focus-visible:ring-4 peer-focus-visible:ring-brand/20 ${
                      enabledRatings.includes(rating) ? "nuvorate-switch-track-on bg-brand" : "bg-black/10"
                    }`}
                  >
                    <span
                      className={`nuvorate-switch-thumb absolute top-1 h-4 w-4 rounded-full bg-white shadow-sm transition-transform duration-200 ${
                        enabledRatings.includes(rating)
                          ? "translate-x-6"
                          : "translate-x-1"
                      }`}
                    />
                  </span>
                </span>
              </label>
            ))}
          </div>
          <button
            type="button"
            disabled={isSaving}
            onClick={handleSave}
            className="self-end rounded-xl bg-brand px-4 py-2.5 text-xs font-semibold text-white transition hover:bg-[#4D4EE8] disabled:cursor-wait disabled:opacity-60"
          >
            {isSaving ? "Zapisywanie..." : "Zapisz ustawienia"}
          </button>
          <AiGenerationProgress
            messages={responseProgressMessages}
            status={progressStatus}
            title="Generowanie odpowiedzi..."
          />
          {toast && (
            <div className="rounded-xl border border-brand/10 bg-brand-soft p-3 text-xs font-semibold leading-5 text-brand">
              {toast}
            </div>
          )}
          {error && (
            <div className="rounded-xl border border-red-100 bg-red-50 p-3 text-xs font-medium leading-5 text-red-600">
              {error}
            </div>
          )}
        </div>
      </div>

      <div className="min-[769px]:hidden">
        <div>
          <p className="text-xs font-medium uppercase tracking-[0.12em] text-black/35">
            Automatyczne odpowiedzi
          </p>
        </div>

        <label className="mt-3 flex items-center justify-between gap-4 rounded-2xl border border-black/[0.06] bg-[#FAFAFC] px-4 py-3">
          <span className="text-sm font-semibold text-ink">Automatyczne generowanie</span>
          <input
            type="checkbox"
            checked={autoGenerate}
            onChange={(event) => setAutoGenerate(event.target.checked)}
            className="peer sr-only"
          />
          <span
            className={`nuvorate-switch-track relative h-6 w-11 shrink-0 rounded-full transition peer-focus-visible:ring-4 peer-focus-visible:ring-brand/20 ${
              autoGenerate ? "nuvorate-switch-track-on bg-brand" : "bg-black/10"
            }`}
          >
            <span
              className={`nuvorate-switch-thumb absolute top-1 h-4 w-4 rounded-full bg-white shadow-sm transition-transform duration-200 ${
                autoGenerate ? "translate-x-6" : "translate-x-1"
              }`}
            />
          </span>
        </label>

        <button
          type="button"
          onClick={() => setIsRatingsSheetOpen(true)}
          className="mt-2 flex w-full items-center justify-between rounded-2xl border border-black/[0.06] bg-[#FAFAFC] px-4 py-3 text-left transition hover:border-brand/20 focus:outline-none focus:ring-4 focus:ring-brand/10"
        >
          <span>
            <span className="block text-sm font-semibold text-ink">Oceny</span>
            <span className="mt-0.5 block text-xs text-black/40">
              {enabledRatings.length > 0
                ? `Wybrane: ${enabledRatings.map(ratingStars).join(" · ")}`
                : "Nie wybrano ocen"}
            </span>
          </span>
          <span className="text-lg leading-none text-black/35" aria-hidden="true">›</span>
        </button>

        {isDirty ? (
          <button
            type="button"
            disabled={isSaving}
            onClick={handleSave}
            className="mt-3 w-full rounded-xl bg-brand px-4 py-3 text-sm font-semibold text-white transition hover:bg-[#4D4EE8] disabled:cursor-wait disabled:opacity-60"
          >
            {isSaving ? "Zapisywanie..." : "Zapisz ustawienia"}
          </button>
        ) : null}
        <AiGenerationProgress
          messages={responseProgressMessages}
          status={progressStatus}
          title="Generowanie odpowiedzi..."
        />
        {toast && (
          <div className="mt-3 rounded-xl border border-brand/10 bg-brand-soft p-3 text-xs font-semibold leading-5 text-brand">
            {toast}
          </div>
        )}
        {error && (
          <div className="mt-3 rounded-xl border border-red-100 bg-red-50 p-3 text-xs font-medium leading-5 text-red-600">
            {error}
          </div>
        )}
      </div>

      {isRatingsSheetOpen && typeof document !== "undefined"
        ? createPortal(
        <div
          className="fixed inset-0 z-[110] bg-ink/20 min-[769px]:hidden"
          role="presentation"
          onMouseDown={(event) => {
            if (event.currentTarget === event.target) {
              setIsRatingsSheetOpen(false);
            }
          }}
        >
          <section
            role="dialog"
            aria-modal="true"
            aria-labelledby="rating-sheet-title"
            className="mobile-bottom-sheet-enter fixed inset-x-0 bottom-0 z-[111] flex max-h-[88dvh] flex-col overflow-hidden rounded-t-[28px] border border-black/[0.06] bg-white shadow-[0_-16px_60px_rgba(15,15,16,0.2)]"
          >
            <div className="min-h-0 flex-1 overflow-y-auto overscroll-contain px-5 pt-5">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <p className="text-xs font-medium uppercase tracking-[0.12em] text-black/35">
                    Automatyczne odpowiedzi
                  </p>
                  <h2 id="rating-sheet-title" className="mt-1 text-xl font-semibold tracking-tight">
                    Wybierz oceny
                  </h2>
                </div>
                <button
                  type="button"
                  onClick={() => setIsRatingsSheetOpen(false)}
                  className="grid h-9 w-9 place-items-center rounded-xl text-lg text-black/45 transition hover:bg-black/[0.04] hover:text-ink focus:outline-none focus:ring-4 focus:ring-brand/10"
                  aria-label="Zamknij wybór ocen"
                >
                  ×
                </button>
              </div>

            <div className="mt-5 divide-y divide-black/[0.06]">
              {[5, 4, 3, 2, 1].map((rating) => (
                <label
                  key={rating}
                  className="flex items-center justify-between gap-5 py-3.5"
                >
                  <span className="text-sm font-semibold text-ink">{rating}★</span>
                  <span className="flex items-center gap-2">
                    <span className="text-[10px] font-semibold uppercase tracking-[0.12em] text-black/30">
                      {enabledRatings.includes(rating) ? "ON" : "OFF"}
                    </span>
                    <input
                      type="checkbox"
                      checked={enabledRatings.includes(rating)}
                      onChange={(event) => toggleRating(rating, event.target.checked)}
                      className="peer sr-only"
                    />
                    <span
                      className={`nuvorate-switch-track relative h-6 w-11 rounded-full transition peer-focus-visible:ring-4 peer-focus-visible:ring-brand/20 ${
                        enabledRatings.includes(rating) ? "nuvorate-switch-track-on bg-brand" : "bg-black/10"
                      }`}
                    >
                      <span
                        className={`nuvorate-switch-thumb absolute top-1 h-4 w-4 rounded-full bg-white shadow-sm transition-transform duration-200 ${
                          enabledRatings.includes(rating)
                            ? "translate-x-6"
                            : "translate-x-1"
                        }`}
                      />
                    </span>
                  </span>
                </label>
              ))}
            </div>
            </div>

            <div className="border-t border-black/[0.06] bg-white px-5 pb-[max(1.25rem,env(safe-area-inset-bottom))] pt-3">
              <button
                type="button"
                onClick={() => setIsRatingsSheetOpen(false)}
                className="w-full rounded-xl bg-brand px-4 py-3 text-sm font-semibold text-white transition hover:bg-[#4D4EE8] focus:outline-none focus:ring-4 focus:ring-brand/20"
              >
                Gotowe
              </button>
            </div>
          </section>
        </div>,
        document.body,
      )
        : null}
    </section>
  );
}
