"use client";

import { useEffect, useState } from "react";
import {
  AiGenerationProgress,
  type AiGenerationProgressStatus,
  responseProgressMessages,
} from "@/components/ui/ai-generation-progress";

type ResponseSettingsCardProps = {
  businessId: string;
  initialAutoGenerate: boolean;
  initialEnabledRatings: number[];
};

type GeneratedResponse = {
  responseText: string;
  reviewId: string;
  status: "ready";
};

function ratingStars(rating: number) {
  return `${"★".repeat(rating)}${"☆".repeat(5 - rating)}`;
}

async function readApiError(response: Response, fallback: string) {
  try {
    const data = await response.json();
    return typeof data?.error === "string" ? data.error : fallback;
  } catch {
    return fallback;
  }
}

export function ResponseSettingsCard({
  businessId,
  initialAutoGenerate,
  initialEnabledRatings,
}: ResponseSettingsCardProps) {
  const [autoGenerate, setAutoGenerate] = useState(initialAutoGenerate);
  const [enabledRatings, setEnabledRatings] = useState(initialEnabledRatings);
  const [isSaving, setIsSaving] = useState(false);
  const [progressStatus, setProgressStatus] =
    useState<AiGenerationProgressStatus>("idle");
  const [error, setError] = useState("");
  const [toast, setToast] = useState("");

  useEffect(() => {
    if (!toast) {
      return;
    }

    const timeout = window.setTimeout(() => setToast(""), 2000);
    return () => window.clearTimeout(timeout);
  }, [toast]);

  async function handleSave() {
    setError("");
    setIsSaving(true);

    try {
      const response = await fetch("/api/responses/settings", {
        body: JSON.stringify({
          autoGenerate,
          businessId,
          enabledRatings,
        }),
        headers: {
          "Content-Type": "application/json",
        },
        method: "PATCH",
      });

      if (!response.ok) {
        throw new Error(
          await readApiError(response, "Nie udało się zapisać ustawień."),
        );
      }

      const data = await response.json();
      setAutoGenerate(Boolean(data?.autoGenerate));
      setEnabledRatings(
        Array.isArray(data?.enabledRatings)
          ? data.enabledRatings.map((value: unknown) => Number(value))
          : enabledRatings,
      );

      if (data?.autoGenerate && enabledRatings.length > 0) {
        setProgressStatus("running");
        const autoGenerateResponse = await fetch("/api/responses/auto-generate", {
          body: JSON.stringify({
            businessId,
            enabledRatings,
          }),
          headers: {
            "Content-Type": "application/json",
          },
          method: "POST",
        });

        if (!autoGenerateResponse.ok) {
          throw new Error(
            await readApiError(
              autoGenerateResponse,
              "Nie udało się automatycznie wygenerować odpowiedzi.",
            ),
          );
        }

        const autoGenerateData = await autoGenerateResponse.json();
        const generatedCount = Number(autoGenerateData?.generatedCount ?? 0);
        const generatedResponses = Array.isArray(autoGenerateData?.generatedResponses)
          ? (autoGenerateData.generatedResponses as GeneratedResponse[])
          : [];

        if (generatedResponses.length > 0) {
          window.dispatchEvent(
            new CustomEvent("nuvorate:responses-generated", {
              detail: {
                generatedResponses,
              },
            }),
          );
        }

        setToast(
          generatedCount > 0
            ? `Wygenerowano ${generatedCount} ${
                generatedCount === 1 ? "odpowiedź" : "odpowiedzi"
              }`
            : "Brak nowych opinii do wygenerowania",
        );
        setProgressStatus("complete");
        window.setTimeout(() => setProgressStatus("idle"), 600);
      } else {
        setProgressStatus("idle");
        setToast("Zapisano");
      }
    } catch (saveError) {
      setError(
        saveError instanceof Error
          ? saveError.message
          : "Nie udało się zapisać ustawień.",
      );
      setProgressStatus("idle");
    } finally {
      setIsSaving(false);
    }
  }

  return (
    <section className="mt-8 rounded-[24px] border border-black/[0.06] bg-white p-5 shadow-card sm:p-6">
      <div className="grid gap-5 lg:grid-cols-[minmax(0,0.95fr)_minmax(300px,0.8fr)] lg:items-start">
        <div>
          <p className="text-xs font-medium uppercase tracking-[0.12em] text-black/35">
            Automatyczne odpowiedzi
          </p>
          <h2 className="mt-1 text-xl font-semibold tracking-tight">
            Ustawienia generowania
          </h2>
          <p className="mt-2 max-w-md text-sm leading-6 text-black/45">
            Wybierz oceny, dla których NuvoRate przygotuje propozycje odpowiedzi
            po zapisaniu ustawień.
          </p>
          <label className="mt-4 flex max-w-md items-center justify-between gap-4 rounded-2xl border border-black/[0.06] bg-[#FAFAFC] px-4 py-3 transition duration-200 hover:border-brand/20 hover:bg-white">
            <span>
              <span className="block text-sm font-semibold text-ink">
                Automatycznie generuj odpowiedzi
              </span>
              <span className="mt-1 block text-xs leading-5 text-black/40">
                NuvoRate przygotuje propozycje dla nowych opinii zgodnie z
                wybranymi ocenami.
              </span>
            </span>
            <input
              type="checkbox"
              checked={autoGenerate}
              onChange={(event) => setAutoGenerate(event.target.checked)}
              className="sr-only"
            />
            <span
              className={`relative h-6 w-11 shrink-0 rounded-full transition ${
                autoGenerate ? "bg-brand" : "bg-black/10"
              }`}
            >
              <span
                className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow-sm transition-transform duration-200 ${
                  autoGenerate ? "translate-x-6" : "translate-x-1"
                }`}
              />
            </span>
          </label>
        </div>
        <div className="flex flex-col gap-3">
          <p className="text-xs font-semibold uppercase tracking-[0.12em] text-black/35">
            Generuj dla ocen
          </p>
          <div className="grid gap-1.5">
            {[5, 4, 3, 2, 1].map((rating) => (
              <label
                key={rating}
                className="flex items-center justify-between gap-5 rounded-xl border border-black/[0.06] bg-[#FAFAFC] px-3.5 py-2 transition duration-200 hover:border-brand/20 hover:bg-white"
              >
                <span className="text-sm font-semibold tracking-[0.04em] text-ink">
                  {ratingStars(rating)}
                </span>
                <span className="flex items-center gap-2">
                  <span className="text-[10px] font-semibold uppercase tracking-[0.12em] text-black/30">
                    {enabledRatings.includes(rating) ? "ON" : "OFF"}
                  </span>
                  <input
                    type="checkbox"
                    checked={enabledRatings.includes(rating)}
                    onChange={(event) => {
                      setEnabledRatings((currentRatings) =>
                        event.target.checked
                          ? [...currentRatings, rating].sort((a, b) => b - a)
                          : currentRatings.filter((value) => value !== rating),
                      );
                    }}
                    className="sr-only"
                  />
                  <span
                    className={`relative h-6 w-11 rounded-full transition ${
                      enabledRatings.includes(rating) ? "bg-brand" : "bg-black/10"
                    }`}
                  >
                    <span
                      className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow-sm transition-transform duration-200 ${
                        enabledRatings.includes(rating)
                          ? "translate-x-6"
                          : "translate-x-1"
                      }`}
                    />
                  </span>
                </span>
              </label>
            ))}
          </div>
          <button
            type="button"
            disabled={isSaving}
            onClick={handleSave}
            className="self-end rounded-xl bg-brand px-4 py-2.5 text-xs font-semibold text-white transition hover:bg-[#4D4EE8] disabled:cursor-wait disabled:opacity-60"
          >
            {isSaving ? "Zapisywanie..." : "Zapisz ustawienia"}
          </button>
          <AiGenerationProgress
            messages={responseProgressMessages}
            status={progressStatus}
            title="Generowanie odpowiedzi..."
          />
          {toast && (
            <div className="rounded-xl border border-brand/10 bg-brand-soft p-3 text-xs font-semibold leading-5 text-brand">
              {toast}
            </div>
          )}
          {error && (
            <div className="rounded-xl border border-red-100 bg-red-50 p-3 text-xs font-medium leading-5 text-red-600">
              {error}
            </div>
          )}
        </div>
      </div>
    </section>
  );
}
