import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { matchAuthorProfiles, safeGoogleUri } from "./google-author-profile-matching.ts";
import { requestAuthorProfiles, allowAuthorRequest, finishAuthorRequest } from "./google-author-profile-request.ts";
import type { GoogleReviewPreview } from "./google-review-mapping.ts";
const gbp: GoogleReviewPreview = { googleReviewId: "a", resourceName: null, author: { displayName: "Anna Nowak", isAnonymous: false, profilePhotoUrl: null }, rating: 5, comment: "Dobry\r\n kontakt", createdAt: "2026-09-01T12:00:00.123456Z", updatedAt: "2026-09-01T12:00:00.123456Z", ownerReply: null };
const place = { rating: 5, originalText: { text: "Dobry kontakt" }, publishTime: "2026-09-01T12:00:00.123456789Z", authorAttribution: { displayName: "Anna Nowak", uri: "https://www.google.com/maps/contrib/123/reviews" } };
test("text match and submillisecond serialization preserve exact official URI", () => { const [r] = matchAuthorProfiles([gbp], [place]); assert.equal(r.status, "UNIQUE_MATCH"); assert.equal(r.authorProfileUri, place.authorAttribution.uri); });
for (const [name, change] of Object.entries({ rating: { rating: 4 }, name: { authorAttribution: { displayName: "Other" } }, text: { originalText: { text: "Other" } }, timestamp: { publishTime: "2026-09-01T12:00:03Z" }, missingTime: { publishTime: undefined }, missingName: { authorAttribution: {} } })) {
  test(`${name} mismatch fails closed`, () => assert.equal(matchAuthorProfiles([gbp], [{ ...place, ...change }])[0].status, "NO_MATCH"));
}
test("even one millisecond difference is rejected", () => assert.equal(matchAuthorProfiles([gbp], [{ ...place, publishTime: "2026-09-01T12:00:00.124Z" }])[0].status, "NO_MATCH"));
test("duplicate candidate is ambiguous", () => assert.equal(matchAuthorProfiles([gbp, { ...gbp, googleReviewId: "b" }], [place])[0].status, "AMBIGUOUS"));
test("empty candidates", () => assert.equal(matchAuthorProfiles([], [place])[0].authorProfileUri, null));
test("anonymous is rejected", () => assert.equal(matchAuthorProfiles([{ ...gbp, author: { ...gbp.author, isAnonymous: true } }], [place])[0].status, "NO_MATCH"));
test("rating-only match and collision", () => { const g = { ...gbp, comment: null }; const p = { ...place, originalText: undefined }; assert.equal(matchAuthorProfiles([g], [p])[0].status, "UNIQUE_MATCH"); assert.equal(matchAuthorProfiles([g,g], [p])[0].status, "AMBIGUOUS"); });
test("missing URI remains null", () => assert.equal(matchAuthorProfiles([gbp], [{ ...place, authorAttribution: { displayName: "Anna Nowak" } }])[0].authorProfileUri, null));
test("original text takes priority", () => assert.equal(matchAuthorProfiles([gbp], [{ ...place, text: { text: "translation" } }])[0].status, "UNIQUE_MATCH"));
test("one-sided text cannot match", () => assert.equal(matchAuthorProfiles([{ ...gbp, comment: null }], [place])[0].status, "NO_MATCH"));
test("duplicate Places candidates fail closed and at most five are processed", () => { const result = matchAuthorProfiles([gbp], Array(6).fill(place)); assert.equal(result.length,5); assert.ok(result.every(r=>r.authorProfileUri===null)); });
for (const uri of ["javascript:alert(1)", "http://www.google.com/maps/contrib/123", "https://google.com.evil.test/maps/contrib/123", "https://evil.test/", "https://user@www.google.com/maps/contrib/123", "https://www.google.com/url?url=evil"]) test(`reject URI ${uri}`, () => assert.equal(safeGoogleUri(uri),null));
for (const status of [400,403,429,500,503]) test(`Places ${status} fails gracefully once`, async () => { let calls=0; const mock = async () => { calls++; return new Response("",{status}); }; assert.deepEqual(await requestAuthorProfiles("place","secret",[gbp],mock),[]); assert.equal(calls,1); });
test("timeout and invalid JSON preserve empty enrichment", async () => { assert.deepEqual(await requestAuthorProfiles("p","s",[gbp],async()=>{throw new DOMException("timeout","TimeoutError");}),[]); assert.deepEqual(await requestAuthorProfiles("p","s",[gbp],async()=>new Response("invalid")),[]); });
test("missing placeId never requests Places", async () => { let calls=0; await requestAuthorProfiles("","s",[gbp],async()=>{calls++;return new Response();}); assert.equal(calls,0); });
test("request is no-store, redirect forbidden, one call and no payload leaks", async () => { let calls=0; const result=await requestAuthorProfiles("p","key",[gbp],async(_url,options)=>{ calls++; assert.equal(options?.cache,"no-store"); assert.equal(options?.redirect,"error"); return Response.json({reviews:[place]}); }); assert.equal(calls,1); assert.equal(result[0].authorProfileUri,place.authorAttribution.uri); assert.ok(!JSON.stringify(result).includes("key")); });
test("rate limit isolates businesses, locks in-flight and expires without retaining content", () => { assert.equal(allowAuthorRequest("a",100),true); assert.equal(allowAuthorRequest("a",101),false); assert.equal(allowAuthorRequest("b",101),true); assert.equal(allowAuthorRequest("a",60100),false); finishAuthorRequest("a"); assert.equal(allowAuthorRequest("a",60100),true); finishAuthorRequest("a"); finishAuthorRequest("b"); });
test("route authorizes before service and scopes both connection and stored reviews", () => { const s=readFileSync("app/api/author-google-profiles/route.ts","utf8"); assert.ok(s.indexOf("hasPlanCapability")<s.indexOf("await requestAuthorProfiles")); assert.match(s,/user.id, "id", "read"/); assert.equal((s.match(/\.eq\("business_id", businessId\)/g)||[]).length,2); assert.doesNotMatch(s,/request\.json|searchParams|console\.|\.upsert\(|\.insert\(/); assert.match(s,/private, no-store/); });
test("UI uses explicit enrichment, neutral state, safe links and dialog",()=>{const s=readFileSync("components/author-verification/author-verification-list.tsx","utf8"); assert.match(s,/target="_blank" rel="noopener noreferrer"/); assert.match(s,/NuvoRate nie potwierdza tożsamości autora/); assert.match(s,/Profil Google autora jest niedostępny/); assert.match(s,/translate="no"/); assert.match(s,/aria-modal="true"/); assert.doesNotMatch(s,/customer|confidence|decisionStatus/);});
